# Generated by Django 4.1.2 on 2024-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('captions', models.TextField(blank=True, max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='gallery')),
                ('captions', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ContactLink',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.RemoveField(
            model_name='imageabout',
            name='page',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='ImageAbout',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='gallery.photo'),
        ),
    ]
